# labelsync - ラベルを同期させる

on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'

jobs:
  label-sync:
    name: auto label sync
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run Label Sync
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
